### ISSUE TITLE
Link previews not showing

### ISSUE THREAD

**Issue by jlubeck** [flyerhq/flutter_chat_ui#25]
I'm using just the sample code provided in your documentation and when I try the link you provide to test (https://bit.ly/2P0cn2g), I don't see a preview, just an extra space:

![Screen Shot 2021-05-18 at 2 53 04 PM](https://user-images.githubusercontent.com/3067603/118707634-c1674b80-b7e8-11eb-9124-6e85f90d8d05.png)

**Comment by jangruenwaldt** [comment]
The extra empty space is also something I'd like to note, if the link cant be resolved, it shouldn't change the appearance.

Link previews in general work for me though, so not sure whats the problem here.

**Comment by demchenkoalex** [comment]
We already marked it as a problem and @Voidozzer is working on that

**Comment by demchenkoalex** [comment]
Both problems are fixed @jlubeck @jangruenwaldt in [v1.0.3](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.0.3). Btw link provided in the doc is not for the link preview test, but for the different image render mode test :) Anyway, good catch.

**Comment by jlubeck** [comment]
hey @demchenkoalex I updated the lib to 1.0.3 and although I no longer see the empty space, the preview is still not showing up for me...

<img width="192" alt="Screen Shot 2021-05-20 at 1 06 01 PM" src="https://user-images.githubusercontent.com/3067603/119020341-213a2f80-b96c-11eb-9e6e-cf40ba3b1991.png">

Also, when I put a link PLUS text, looks like they are not properly allgned:
<img width="250" alt="Screen Shot 2021-05-20 at 1 05 41 PM" src="https://user-images.githubusercontent.com/3067603/119020306-15e70400-b96c-11eb-8b63-19050663253b.png">

**Comment by demchenkoalex** [comment]
Hi @jlubeck what setup are you using? must be something with a firewall or project settings or Idk, cause we had a problem with a preview where the whole link is an image (which I fixed) but never for a regular preview. Checking alignment.

**Comment by jlubeck** [comment]
I'm trying to debug this myself... actually found another issue in the meantime:
![Screen Shot 2021-05-20 at 1 29 11 PM](https://user-images.githubusercontent.com/3067603/119023084-5e53f100-b96f-11eb-8de8-59de89f2c2c4.png)
This piece of code is creating a wrong URL if you use capital letters on the url (like HTTPS://flyer.com) 

This `if (!url.startsWith('http')) {` should probably be `if (!url.toLowerCase().startsWith('http')) {`

Will get back to you if I find the cause of the previewer not working when using a valid URL

**Comment by jlubeck** [comment]
Trying to find where this is failing, doesn't seem to be a firewall issue since the `PreviewData` is being filled with all the proper info, even the image url, and it's size (so it got to load the actual image in memory)

But I got a bit lost in the code base, of what does this line (inside `text_message`) do to actually render the file inside the message? 
![Screen Shot 2021-05-20 at 1 41 02 PM](https://user-images.githubusercontent.com/3067603/119024407-061dee80-b971-11eb-8b5a-ccc0c431c39f.png)

**Comment by jlubeck** [comment]
Ok, thank you for that, made me realize that I didn't properly read the documentation and I was expecting the preview to appear automatically instead of having to implement the `onPreviewDataFetched` on the `Chat` widget. 

So all good now! Good thing we found other small issues so I don't feel like I completely wasted your time 😅

**Comment by demchenkoalex** [comment]
So this Https thing is fixed on main (will not release since it is a really small change), thanks for noticing, alignment is a bit trickier, it is wrong in the library we use https://github.com/Cretezy/flutter_linkify will check tomorrow if I will be able to fix it there..

**Comment by demchenkoalex** [comment]
Ok, everything is fixed in [v1.0.5](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.0.5)

**Comment by jlubeck** [comment]
NICEEEE looking good!!!
